# Generated by Django 4.2.11 on 2026-09-21 18:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bus/operators/')),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bus Operator',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(max_length=150)),
                ('to_city', models.CharField(max_length=150)),
                ('distance_km', models.PositiveIntegerField(default=0)),
                ('estimated_duration', models.CharField(blank=True, help_text='e.g. 3h 30m', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='bus.busoperator')),
            ],
            options={
                'verbose_name': 'Bus Route',
                'ordering': ['from_city', 'to_city'],
                'unique_together': {('operator', 'from_city', 'to_city')},
            },
        ),
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('seat_class', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('ac', 'AC Sleeper'), ('non_ac', 'Non-AC')], default='economy', max_length=20)),
                ('total_seats', models.PositiveIntegerField(default=40)),
                ('available_seats', models.PositiveIntegerField(default=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='bus.busroute')),
            ],
            options={
                'verbose_name': 'Bus Schedule',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='BusBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('booking_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_mobile', models.CharField(blank=True, max_length=20)),
                ('passenger_count', models.PositiveIntegerField(default=1)),
                ('seat_numbers', models.CharField(blank=True, help_text='e.g. A1,A2,B3', max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=15)),
                ('booked_by_role', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('ambassador', 'Ambassador'), ('admin', 'Admin')], default='customer', max_length=15)),
                ('booked_by_email', models.EmailField(blank=True, help_text='Email of staff/ambassador who made booking', max_length=254)),
                ('special_requests', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bus.busschedule')),
            ],
            options={
                'verbose_name': 'Bus Booking',
                'ordering': ['-booked_at'],
            },
        ),
    ]
