# Generated by Django 6.1 on 2026-08-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('support_member', 'Support Member'), ('tenant_admin', 'Tenant Admin'), ('tenant_staff', 'Tenant Staff'), ('customer', 'Customer')], db_index=True, default='customer', max_length=20),
        ),
    ]
