# Generated by Django 4.2.11 on 2026-09-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('support_member', 'Support Member'), ('tenant_admin', 'Tenant Admin'), ('tenant_staff', 'Tenant Staff'), ('ambassador', 'Ambassador'), ('customer', 'Customer')], db_index=True, default='customer', max_length=20),
        ),
    ]
