# Generated by Django 4.2.11 on 2026-09-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_accountheadgroup_agencyagent_agencycompany_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visalot',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='visalot',
            name='okala',
        ),
        migrations.RemoveField(
            model_name='visalot',
            name='status',
        ),
        migrations.AddField(
            model_name='visalot',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visalot',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='visa_lots/'),
        ),
        migrations.AddField(
            model_name='visalot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='visalot',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Visa fee per person (leave blank if not applicable)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='visalot',
            name='processing_time',
            field=models.CharField(blank=True, help_text='e.g. 7-10 business days', max_length=150),
        ),
        migrations.AddField(
            model_name='visalot',
            name='requirements',
            field=models.TextField(blank=True, help_text='List of required documents'),
        ),
        migrations.AddField(
            model_name='visalot',
            name='show_on_website',
            field=models.BooleanField(default=True, help_text='Display this visa lot on the agency public website'),
        ),
        migrations.AddField(
            model_name='visalot',
            name='sponsor_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visalot',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='visalot',
            name='title',
            field=models.CharField(default='Visa Lot', max_length=255),
        ),
        migrations.AddField(
            model_name='visalot',
            name='visa_type',
            field=models.CharField(blank=True, choices=[('work', 'Work Visa'), ('tourist', 'Tourist Visa'), ('business', 'Business Visa'), ('student', 'Student Visa'), ('domestic', 'Domestic Worker Visa'), ('transit', 'Transit Visa'), ('family', 'Family Visa'), ('other', 'Other')], default='work', max_length=20),
        ),
        migrations.AlterField(
            model_name='visalot',
            name='lot_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='visalot',
            name='quota',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Okala',
        ),
    ]
