# Generated by Django 4.2.11 on 2026-09-27 06:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_visalot_options_remove_visalot_okala_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Auto-calculated due balance', max_digits=12),
        ),
        migrations.AddField(
            model_name='candidate',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount collected so far', max_digits=12),
        ),
        migrations.AddField(
            model_name='candidate',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total agreed visa/package fee', max_digits=12),
        ),
        migrations.CreateModel(
            name='CandidatePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('bKash / Mobile Banking', 'bKash / Mobile Banking'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='Cash', max_length=50)),
                ('reference_no', models.CharField(blank=True, help_text='Txn ID / Cheque # / Slip #', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.candidate')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
