# Generated by Django 4.2.11 on 2026-09-27 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_candidate_due_amount_candidate_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='applicable_sectors',
            field=models.JSONField(blank=True, default=list, help_text='List of required sectors for candidate workflow'),
        ),
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('passport', 'Passport / Bio Data'), ('selection', 'Selection & Assessment'), ('medical', 'Medical Clearance'), ('police_clearance', 'Police Clearance'), ('mofa', 'MOFA Document'), ('enjaz', 'Enjaz / Payment Receipt'), ('fingerprint', 'Biometric / Fingerprint'), ('visa_stamping', 'Visa Stamping Document'), ('training', 'Training Certificate'), ('manpower', 'Manpower / BMET Smart Card'), ('flight', 'Ticket & NOC Approval'), ('other', 'Other Document')], default='passport', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='candidate_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenants.candidate')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
