# Generated by Django 4.2.11 on 2026-09-27 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_candidate_applicable_sectors_candidatedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepayment',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_payments', to='tenants.accountvoucher'),
        ),
    ]
