# Generated by Django 4.2.11 on 2026-10-03 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_candidatepayment_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short description of the expense', max_length=255)),
                ('category', models.CharField(choices=[('rent', 'Office Rent'), ('utilities', 'Electricity & Utilities'), ('internet', 'Internet & Phone'), ('salary', 'Staff Salary'), ('stationery', 'Stationery & Supplies'), ('transport', 'Transport & Fuel'), ('maintenance', 'Maintenance & Repair'), ('marketing', 'Marketing & Advertising'), ('food', 'Food & Entertainment'), ('equipment', 'Equipment & Furniture'), ('software', 'Software & Subscriptions'), ('medical', 'Medical/Health Expense'), ('government', 'Government Fees & Taxes'), ('other', 'Other Expense')], default='other', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('bkash', 'bKash / Mobile Banking'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=30)),
                ('paid_to', models.CharField(blank=True, help_text='Vendor / Payee name', max_length=200)),
                ('reference_no', models.CharField(blank=True, help_text='Receipt/Invoice number', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='office_expenses/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
