# Generated by Django 6.1 on 2026-08-21 07:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('package_type', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], default='starter', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('badge_color', models.CharField(default='primary', max_length=20)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('trial_days', models.PositiveIntegerField(default=14)),
                ('max_users', models.IntegerField(default=5, help_text='-1 for unlimited')),
                ('max_travel_packages', models.IntegerField(default=10, help_text='-1 for unlimited')),
                ('max_visa_services', models.IntegerField(default=5, help_text='-1 for unlimited')),
                ('max_staff', models.IntegerField(default=2, help_text='-1 for unlimited')),
                ('storage_limit_mb', models.IntegerField(default=512, help_text='-1 for unlimited')),
                ('custom_domain', models.BooleanField(default=False)),
                ('advanced_analytics', models.BooleanField(default=False)),
                ('advanced_cms', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('api_access', models.BooleanField(default=False)),
                ('white_label', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Package',
                'verbose_name_plural': 'Subscription Packages',
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('trial', 'Trial')], default='monthly', max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending_payment', 'Pending Payment'), ('suspended', 'Suspended')], default='trial', max_length=20)),
                ('auto_renew', models.BooleanField(default=True)),
                ('expiry_7day_notified', models.BooleanField(default=False)),
                ('expiry_3day_notified', models.BooleanField(default=False)),
                ('expiry_1day_notified', models.BooleanField(default=False)),
                ('expired_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.tenant')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionpackage')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaaSPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('trial', 'Trial')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_payments', to='tenants.tenant')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.subscription')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionpackage')),
            ],
            options={
                'verbose_name': 'SaaS Payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
