# Generated by Django 4.2.11 on 2026-09-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpackage',
            name='air_ticket_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='bus_ticket_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='max_air_routes',
            field=models.IntegerField(default=5, help_text='-1 for unlimited'),
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='max_ambassadors',
            field=models.IntegerField(default=2, help_text='-1 for unlimited'),
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='max_bus_routes',
            field=models.IntegerField(default=5, help_text='-1 for unlimited'),
        ),
    ]
