# Generated by Django 4.2.11 on 2026-09-29 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_airline_flightroute_flightschedule_airticketbooking'),
        ('bus', '0001_initial'),
        ('travel_packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='connected_bus_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_packages', to='bus.busschedule'),
        ),
    ]
