# Generated by Django 4.2.11 on 2026-09-29 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0002_airline_flightroute_flightschedule_airticketbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_by_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_by_role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('staff', 'Staff'), ('ambassador', 'Ambassador')], default='customer', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_bookings', to=settings.AUTH_USER_MODEL, db_constraint=False),
        ),
    ]
