# Generated by Django 4.2.11 on 2026-10-03 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_packages', '0002_travelpackage_connected_bus_schedule_and_more'),
        ('bookings', '0003_booking_booked_by_email_booking_booked_by_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airticketbooking',
            name='schedule',
        ),
        migrations.AlterUniqueTogether(
            name='flightroute',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='flightroute',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='flightschedule',
            name='route',
        ),
        migrations.DeleteModel(
            name='Airline',
        ),
        migrations.DeleteModel(
            name='AirTicketBooking',
        ),
        migrations.DeleteModel(
            name='FlightRoute',
        ),
        migrations.DeleteModel(
            name='FlightSchedule',
        ),
    ]
