# Generated by Django 4.2.11 on 2026-10-09 17:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_airticketbooking_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, help_text='IATA code e.g. BG, BS', max_length=10, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='airlines/logos/')),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Airline',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FlightRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('from_city', models.CharField(max_length=150)),
                ('from_airport_code', models.CharField(blank=True, help_text='IATA e.g. DAC', max_length=5)),
                ('to_city', models.CharField(max_length=150)),
                ('to_airport_code', models.CharField(blank=True, help_text='e.g. DXB', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='bookings.airline')),
            ],
            options={
                'verbose_name': 'Flight Route',
                'ordering': ['from_city', 'to_city'],
                'unique_together': {('airline', 'flight_number')},
            },
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('cabin_class', models.CharField(choices=[('economy', 'Economy'), ('premium_economy', 'Premium Economy'), ('business', 'Business'), ('first', 'First Class')], default='economy', max_length=20)),
                ('total_seats', models.PositiveIntegerField(default=150)),
                ('available_seats', models.PositiveIntegerField(default=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('baggage_allowance', models.CharField(blank=True, help_text='e.g. 23kg', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='bookings.flightroute')),
            ],
            options={
                'verbose_name': 'Flight Schedule',
                'ordering': ['departure_datetime'],
            },
        ),
        migrations.CreateModel(
            name='AirTicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('booking_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_mobile', models.CharField(blank=True, max_length=20)),
                ('passenger_count', models.PositiveIntegerField(default=1)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('pnr_number', models.CharField(blank=True, max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=15)),
                ('booked_by_role', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('ambassador', 'Ambassador'), ('admin', 'Admin')], default='customer', max_length=15)),
                ('booked_by_email', models.EmailField(blank=True, help_text='Email of staff/ambassador who made the booking', max_length=254)),
                ('special_requests', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.flightschedule')),
            ],
            options={
                'verbose_name': 'Air Ticket Booking',
                'ordering': ['-booked_at'],
            },
        ),
    ]
