# Generated by Django 6.1 on 2026-08-21 07:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYCRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_email', models.EmailField(db_index=True, max_length=254)),
                ('customer_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driving_license', 'Driving License'), ('birth_certificate', 'Birth Certificate')], max_length=25)),
                ('document_number', models.CharField(max_length=100)),
                ('document_front', models.ImageField(upload_to='kyc/documents/')),
                ('document_back', models.ImageField(blank=True, null=True, upload_to='kyc/documents/')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='kyc/selfies/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
