# Generated by Django 6.1 on 2026-08-21 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('application_code', models.CharField(max_length=20, unique=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_mobile', models.CharField(blank=True, max_length=20)),
                ('passport_number', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('intended_travel_date', models.DateField(blank=True, null=True)),
                ('duration_of_stay', models.PositiveIntegerField(default=30, help_text='Days')),
                ('purpose_of_visit', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Visa Application',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='VisaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Passport Copy'), ('photo', 'Passport Photo'), ('bank_statement', 'Bank Statement'), ('invitation', 'Invitation Letter'), ('hotel_booking', 'Hotel Booking'), ('flight_ticket', 'Flight Ticket'), ('other', 'Other Document')], max_length=30)),
                ('file', models.FileField(upload_to='visa/documents/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='visa.visaapplication')),
            ],
        ),
        migrations.CreateModel(
            name='VisaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('visa_type', models.CharField(choices=[('tourist', 'Tourist Visa'), ('business', 'Business Visa'), ('student', 'Student Visa'), ('work', 'Work Visa'), ('transit', 'Transit Visa'), ('family', 'Family Visa'), ('other', 'Other')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processing_time', models.CharField(help_text='e.g. 5-7 business days', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True, help_text='List of required documents')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='visa/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visa_services', to='destinations.country')),
            ],
            options={
                'verbose_name': 'Visa Service',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='visa_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='visa.visaservice'),
        ),
    ]
