# Generated by Django 6.1 on 2026-08-21 07:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('notification_type', models.CharField(choices=[('booking', 'Booking'), ('visa', 'Visa Application'), ('payment', 'Payment'), ('subscription', 'Subscription'), ('support', 'Support Ticket'), ('system', 'System'), ('general', 'General')], default='general', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
